# Generated by Django 5.2.8 on 2025-11-27 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_dob', models.DateField()),
                ('patient_phone', models.CharField(blank=True, max_length=20)),
                ('medication_name', models.CharField(max_length=100)),
                ('medication_dose', models.CharField(max_length=100)),
                ('medication_order_date', models.DateField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('INS_VERIFY', 'Verifying Insurance'), ('PA', 'Prior Auth'), ('INFO_REQ', 'Info Requested'), ('READY', 'Ready for Review')], default='NEW', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('patient_name', 'patient_dob', 'medication_name', 'medication_order_date')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_by', models.CharField(max_length=50)),
                ('event_type', models.CharField(choices=[('NOTE', 'Note'), ('INS', 'Insurance call'), ('STATUS', 'Status Change'), ('OTHER', 'Other')], default='NOTE', max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workflow.prescription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
